language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 4
script:
  - npm i -g webpack-cli
  - yarn build
deploy:
  provider: firebase
  skip-cleanup: true
  keep-history: true
  token: $FIREBASE_CI
  project: "comics-react"
  local-dir: ./dist
  target-branch: main
  commit_message: "deploy del proyecto"
  on:
    branch: main